-- Sequences
CREATE SEQUENCE SEQ_CUSTOMER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ACCOUNT  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- CUSTOMER table
CREATE TABLE CUSTOMER (
  ID            NUMBER(19)    PRIMARY KEY,
  FULL_NAME     VARCHAR2(200) NOT NULL,
  NATIONAL_ID   VARCHAR2(40)  NOT NULL UNIQUE,
  EMAIL         VARCHAR2(200) NOT NULL UNIQUE,
  KYC_STATUS    VARCHAR2(32)  DEFAULT 'PENDING' NOT NULL,
  CREATED_AT    TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL
);

-- ACCOUNT table
CREATE TABLE ACCOUNT (
  ID           NUMBER(19)    PRIMARY KEY,
  CUSTOMER_ID  NUMBER(19)    NOT NULL,
  TYPE         VARCHAR2(32)  NOT NULL,         -- e.g., SAVINGS, CHECKING
  CURRENCY     VARCHAR2(3)   NOT NULL,         -- e.g., PEN, USD
  OPENED_AT    TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
  STATUS       VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT FK_ACCOUNT_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

-- (Optional) Simple indexes
CREATE INDEX IX_ACCOUNT_CUSTOMER ON ACCOUNT(CUSTOMER_ID);
